; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_CATERPIE   ; 10
	const DEX_METAPOD    ; 11
	const DEX_BUTTERFREE ; 12
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_PIDGEY     ; 16
	const DEX_PIDGEOTTO  ; 17
	const DEX_PIDGEOT    ; 18
	const DEX_PIKACHU    ; 19
	const DEX_RAICHU     ; 20
	const DEX_NIDORAN    ; 21
	const DEX_NIDORINO   ; 22
	const DEX_NIDOKING   ; 23
	const DEX_MANKEY     ; 24
	const DEX_PRIMEAPE   ; 25
	const DEX_EKANS      ; 26
	const DEX_ARBOK      ; 27
	const DEX_WOOPER     ; 28
	const DEX_QUAGSIRE   ; 29
	const DEX_SKWOVET    ; 30
	const DEX_GREEDENT   ; 31
	const DEX_CLEFAIRY   ; 32
	const DEX_CLEFABLE   ; 33
	const DEX_ZUBAT      ; 34
	const DEX_GOLBAT     ; 35
	const DEX_VENONAT    ; 36
	const DEX_VENOMOTH   ; 37
	const DEX_VULPIX     ; 38
	const DEX_NINETALES  ; 39
	const DEX_ABRA       ; 40
	const DEX_KADABRA    ; 41
	const DEX_ALAKAZAM   ; 42
	const DEX_SLOWPOKE   ; 43
	const DEX_SLOWBRO    ; 44
	const DEX_ONIX       ; 45
	const DEX_MAGIKARP   ; 46
	const DEX_GYARADOS   ; 47
	const DEX_MAREEP     ; 48
	const DEX_FLAAFFY    ; 49
	const DEX_AMPHAROS   ; 50
	const DEX_DIGLETT    ; 51
	const DEX_DUGTRIO    ; 52
	const DEX_MEOWTH     ; 53
	const DEX_PERSIAN    ; 54
	const DEX_PSYDUCK    ; 55
	const DEX_GOLDUCK    ; 56
	const DEX_RALTS      ; 57
	const DEX_KIRLIA     ; 58
	const DEX_GARDEVOIR  ; 59
	const DEX_GROWLITHE  ; 60
	const DEX_ARCANINE   ; 61
	const DEX_BOUNSWEET  ; 62
	const DEX_STEENEE    ; 63
	const DEX_TSAREENA   ; 64
	const DEX_MILTANK    ; 65
	const DEX_VOLTORB    ; 66
	const DEX_ELECTRODE  ; 67
	const DEX_EEVEE      ; 68
	const DEX_VAPOREON   ; 69
	const DEX_JOLTEON    ; 70
	const DEX_FLAREON    ; 71
	const DEX_ESPEON     ; 72
	const DEX_LEAFEON    ; 73
	const DEX_GIBLE      ; 74
	const DEX_GABITE     ; 75
	const DEX_GARCHOMP   ; 76
	const DEX_PONYTA     ; 77
	const DEX_RAPIDASH   ; 78
	const DEX_DUCKLETT   ; 79
	const DEX_SWANNA     ; 80
	const DEX_MAGNEMITE  ; 81
	const DEX_MAGNETON   ; 82
	const DEX_SALANDIT   ; 83
	const DEX_SALAZZLE   ; 84
	const DEX_DODUO      ; 85
	const DEX_DODRIO     ; 86
	const DEX_SHELLDER   ; 87
	const DEX_CLOYSTER   ; 88
	const DEX_GASTLY     ; 89
	const DEX_HAUNTER    ; 90
	const DEX_GENGAR     ; 91
	const DEX_EXEGGCUTE  ; 92
	const DEX_EXEGGUTOR  ; 93
	const DEX_CUBONE     ; 94
	const DEX_MAROWAK    ; 95
	const DEX_LICKITUNG  ; 96
	const DEX_RHYHORN    ; 97
	const DEX_RHYDON     ; 98
	const DEX_CHANSEY    ; 99
	const DEX_KANGASKHAN ; 100
	const DEX_HORSEA     ; 101
	const DEX_SEADRA     ; 102
	const DEX_GOLDEEN    ; 103
	const DEX_SEAKING    ; 104
	const DEX_STARYU     ; 105
	const DEX_STARMIE    ; 106
	const DEX_HITMONCHAN ; 107
	const DEX_SCYTHER    ; 108
	const DEX_TAUROS     ; 109
	const DEX_WAILMER    ; 110
	const DEX_WAILORD    ; 111
	const DEX_MILOTIC    ; 112
	const DEX_DRIFLOON   ; 113
	const DEX_DRIFBLIM   ; 114
	const DEX_LOPUNNY    ; 115
	const DEX_CROAGUNK   ; 116
	const DEX_TOXICROAK  ; 117
	const DEX_SIGILYPH   ; 118
	const DEX_LAPRAS     ; 119
	const DEX_ELECTABUZZ ; 120
	const DEX_MAGMAR     ; 121
	const DEX_CHANDELURE ; 122
	const DEX_MAMOSWINE  ; 123
	const DEX_FROSLASS   ; 124
	const DEX_JOLTIK     ; 125
	const DEX_GALVANTULA ; 126
	const DEX_GOLETT     ; 127
	const DEX_GOLURK     ; 128
	const DEX_FRIGIBAX   ; 129
	const DEX_ARCTIBAX   ; 130
	const DEX_BAXCALIBUR ; 131	
	const DEX_LARVITAR   ; 132
	const DEX_PUPITAR    ; 133
	const DEX_TYRANITAR  ; 134
	const DEX_LUCARIO    ; 135	
	const DEX_OMANYTE    ; 136
	const DEX_OMASTAR    ; 136
	const DEX_KABUTO     ; 138
	const DEX_KABUTOPS   ; 139
	const DEX_AERODACTYL ; 140
	const DEX_ANORITH    ; 141
	const DEX_ARMALDO    ; 142
	const DEX_SNORLAX    ; 143
	const DEX_ARTICUNO   ; 144
	const DEX_LANDORUS   ; 145
	const DEX_SPECTRIER  ; 146
	const DEX_DRATINI    ; 147
	const DEX_DRAGONAIR  ; 148
	const DEX_DRAGONITE  ; 149
	const DEX_MEWTWO     ; 150
	const DEX_MEW        ; 151

DEF NUM_POKEMON EQU const_value - 1
